version: "3.1"

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    # stdin_open: true # Equivalent to `-it`
    # tty: true # Equivalent to `-it`
